default-catalog: local

catalog:
  local:
    uri: http://iceberg-rest:8181
    py-io-impl: pyiceberg.io.pyarrow.PyArrowFileIO
    s3.endpoint: http://minio:9000
    s3.access-key-id: admin
    s3.secret-access-key: password